# Generated by Django 5.0.4 on 2026-03-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=64, unique=True)),
                ("theme", models.CharField(default="Firecat Dark", max_length=40)),
                ("mode", models.CharField(default="dark", max_length=10)),
                ("bg_color", models.CharField(default="#0f0f0f", max_length=7)),
                ("accent", models.CharField(default="#FF5722", max_length=7)),
                ("show_shortcuts", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "preferences",
            },
        ),
    ]
